version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
    - "8080:80"
    volumes:
    - ./src:/var/www
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - lumen

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - lumen


networks:
  lumen:
    driver: bridge
